---
    platform: linux
    image_resource:
        type: docker-image
        source:
            repository: node
            tag: 6.9.1
    run:
        path: ci/scripts/lint.sh
        dir: master-installed
    inputs:
        -   name: master-installed
