---
    platform: linux
    image_resource:
        type: docker-image
        source:
            repository: node
            tag: 6.9.1
    run:
        path: ci/scripts/publish.sh
        dir: master-written-package
    inputs:
        -   name: master-written-package
